import Head from "next/head";
import Link from "next/link";
import Footer from "@/components/Footer";

export default function ChampionSkinsPage() {
  return (
    <>
      <Head>
        <title>Champion Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h1>Champion Skins</h1>
        <Link href={"/"}>&larr; Home</Link>
      </header>
      <main>
        <p>Work in progress</p>
      </main>
    </>
  );
}
