import Head from "next/head";
import styled from "styled-components";
import Link from "next/link";
import Footer from "@/components/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>League Collection App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h1>League Collection Tracker</h1>
      </header>
      <StyledSection>
        <small>
          &quot;League Collection Tracker&quot; is not endorsed by Riot Games
          and does not reflect the views or opinions of Riot Games or anyone
          officially involved in producing or managing Riot Games properties.
          Riot Games and all associated properties are trademarks or registered
          trademarks of Riot Games, Inc
        </small>
      </StyledSection>
      <StyledMain>
        <Link href={"/champion-gallery"}>Champion Gallery</Link>
        <Link href={"/champion-skins"}>Champion Skins</Link>
      </StyledMain>
    </>
  );
}

const StyledMain = styled.main`
  flex-grow: 1;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  padding: 6rem;
  border: solid red;
`;

const StyledSection = styled.section`
  width: 90vw;
  border: solid red;
`;
