import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import Footer from "@/components/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>League Collection App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h1>League Collection Tracker</h1>
      </header>
      <section className={styles.section}>
        <p>
          &quot;League Collection Tracker&quot; is not endorsed by Riot Games
          and does not reflect the views or opinions of Riot Games or anyone
          officially involved in producing or managing Riot Games properties.
          Riot Games and all associated properties are trademarks or registered
          trademarks of Riot Games, Inc
        </p>
      </section>
      <main className={styles.main}>
        <Link href={"/ChampionGallery"}>Champion Gallery</Link>
      </main>
      <Footer />
    </>
  );
}
