import Link from "next/link";
import Footer from "@/components/Footer";
import ChampionCart from "@/components/ChampionCard";
import Head from "next/head";

import data from "@/lib/championFull.json";
import test from "@/lib/lolchamp.json";
import styles from "@/styles/ChampionGallery.module.css";

export default function ChampionGalleryPage() {
  const champions = Object.values(data.data);

  // let newSortedChampions = [];
  // for (const [key, value] of Object.entries(data.data)) {
  //   newSortedChampions.push({
  //     id: key.replace(/\s+/g, ""),
  //     name: key,
  //     value,
  //   });
  // }

  const sortedChampions = champions.sort((a, b) => {
    if (a.id < b.id) {
      return -1;
    }
    if (a.id > b.id) {
      return 1;
    }
    return 0;
  });

  return (
    <>
      <Head>
        <title>Champion Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h1>Champion Gallery</h1>
        <Link href={"/"}>&larr; Home</Link>
      </header>
      <main>
        <h2 className={styles.h2}>Champions</h2>
        <p className={styles.p}>{`0 of ${sortedChampions.length}`}</p>
        <ul className={styles.ul}>
          {sortedChampions.map((champion) => {
            return <ChampionCart key={champion.id} champion={champion} />;
          })}
        </ul>
      </main>
      <Footer />
    </>
  );
}
