import Link from "next/link";
import Footer from "@/components/Footer";
import ChampionCard from "@/components/ChampionCard";
import Head from "next/head";
import { useState, useEffect } from "react";

import styles from "@/styles/ChampionGallery.module.css";

export default function ChampionGalleryPage() {
  const [championData, setChampionData] = useState([]);
  const [versions, setVersions] = useState([]);

  useEffect(() => {
    async function fetchData() {
      try {
        // Fetch data from url1
        const responseVersion = await fetch(
          "https://ddragon.leagueoflegends.com/api/versions.json"
        );
        if (!responseVersion.ok) {
          throw new Error(`HTTP error! status: ${responseVersion.status}`);
        }
        const versions = await responseVersion.json();
        setVersions(versions);

        // Fetch data from url2 using data from url1
        const responseChampionFull = await fetch(
          `http://ddragon.leagueoflegends.com/cdn/${versions[0]}/data/en_US/championFull.json`
        );
        if (!responseChampionFull.ok) {
          throw new Error(`HTTP error! status: ${responseChampionFull.status}`);
        }
        const championData = await responseChampionFull.json();
        setChampionData(championData);

        setLoading(false);
      } catch (error) {
        console.error("Error fetching data:", error);
        // handle the error here, e.g. show an error message to the user
      }
    }

    fetchData();
  }, []);

  const sortedChampions = Object.values(championData.data).sort((a, b) => {
    if (a.name < b.name) {
      return -1;
    }
    if (a.name > b.name) {
      return 1;
    }
    return 0;
  });

  return (
    <>
      <Head>
        <title>Champion Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h1>Champion Gallery</h1>
        <Link href={"/"}>&larr; Home</Link>
      </header>
      <main>
        <h2 className={styles.h2}>Champions</h2>
        <h3>Version: {versions[0]}</h3>
        <p className={styles.p}>{`0 of ${sortedChampions.length}`}</p>
        <ul className={styles.ul}>
          {sortedChampions.map((champion) => {
            return <ChampionCard key={champion.id} champion={champion} />;
          })}
        </ul>
      </main>
      <Footer />
    </>
  );
}
